name       : polkit-qt-1
version    : 0.112
release    : 1
source     :
    - git|git://anongit.kde.org/polkit-qt-1.git : 50624e06e88aabd7ae123ad6a4495630f81cd706
license    : LGPL-2.1
component  : programming
summary    : Qt wrapper around polkit-1
description: |
    polkit-qt-1 aims to make it easy for Qt developers to take advantage of polkit API. It is a convenience wrapper around QAction and QAbstractButton that lets you integrate those two components easily with polkit.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(gobject-introspection-1.0)
    - pkgconfig(polkit-agent-1)
    - pkgconfig(Qt5Core)
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
